name = "Nnetsauce"
uuid = "efe80079-2d8f-4399-9724-693920340b4d"
authors = ["thierrymoudiki <thierry.moudiki@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
