name = "Nnetsauce"
uuid = "efe80079-2d8f-4399-9724-693920340b4d"
authors = ["thierrymoudiki <thierry.moudiki@gmail.com>"]
version = "0.16.8"

[compat]
julia = "1.10"
Pkg = "1.6.7"
PyCall = "1.96.4"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[preferences.NetCDF_jll]
libnetcdf_path = "/Users/gong/miniforge3/lib/libnetcdf.19.dylib"
